spring.application.name=siwPolls
#==================================
# = Datasource
#==================================
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=error

logging.level.it.uniroma3.siw.service=info
logging.level.it.uniroma3.siw.GlobalExceptionHandler=info
logging.level.it.uniroma3.siw.config=debug

spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
spring.datasource.url=jdbc:p6spy:postgresql://localhost:5432/Polls
spring.datasource.username=postgres
spring.datasource.password=Alessio09!
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#==================================
# = Web server
#==================================
server.port=8080
#==================================
# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
#==================================
# = Messages configuration 
#==================================
 spring.messages.basename=messages/messages 
 spring.messages.encoding=ISO-8859-1
spring.jpa.properties.hibernate.format_sql=true
 spring.jpa.properties.hibernate.highlight_sql=true
#==================================
# = Variabili di configurazione
#==================================
 app.frontend.url=http://localhost:5173
 app.upload.dir=../uploads_immagini/